# This model must to be extend by the model generated by RestfulAuthentication
class User < Person
  validates_presence_of :civility_id, :country_id
  
  belongs_to :civility

  has_one :cart
  has_one :wishlist
  has_one :address_delivery, :order => 'id desc'
  has_one :address_invoice, :order => 'id desc'
  has_many :addresses
  has_many :address_deliveries, :order =>  'id desc'
  has_many :address_invoices, :order => 'id desc'

  has_and_belongs_to_many   :user_categories, :readonly => true

  accepts_nested_attributes_for :address_deliveries, :address_delivery, :address_invoices, :address_invoices
  attr_accessible :address_deliveries_attributes, :address_delivery_attributes, :address_invoices_attributes, :address_invoice_attributes

  has_many :orders, :order => 'id desc'
  has_and_belongs_to_many :attachments, :list => true, :order => 'position'
  has_and_belongs_to_many :attachments2, :list => true, :order => 'position', :join_table => 'attachments_elements', :foreign_key => 'element_id', :association_foreign_key => 'attachment_id', :class_name => 'Attachment'

  def age
    ((Date.today - self.birthday) / 365).floor
  end

  def total_orders
    self.orders.collect(&:total).sum
  end
end
